# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

addons:
  apt:
    update: true
    packages:
      - gcc
      - g++
      - libblas-dev
      - liblapack-dev
      - libncurses5-dev
      - libreadline-dev
      - libjpeg-dev
      - libpng-dev
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - cdbs
      - qpdf
      - texinfo
      - libmagickcore-dev
      - libmagick++-dev
      - libssh2-1-dev
      - gfortran

env:
  -_R_CHECK_FORCE_SUGGESTS_=false

warnings_are_errors: true
sudo: false
cache: packages
