# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

addons:
  apt:
    packages:
      - libmagickcore-dev

env:
  -_R_CHECK_FORCE_SUGGESTS_=false

warnings_are_errors: true
sudo: false
cache: packages
